# Generated by Django 4.1 on 2022-09-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("authors", models.CharField(max_length=100)),
                ("published_data", models.IntegerField()),
                ("categories", models.CharField(max_length=100)),
                ("thumbnail", models.TextField()),
            ],
        ),
    ]
