# Generated by Django 4.1 on 2022-09-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="authors",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="categories",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="published_data",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="thumbnail",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
