# Generated by Django 4.1 on 2022-09-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0003_rename_published_data_book_published_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="book_id",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
